stages:
  - verify
  - test

variables:
  TAG_ID: gitlab_ci
  PRODUCER_DEV_REGISTRY: registry.petuum.com/internal/pl/daisy/producer/dev
  PRODUCER_PROD_REGISTRY: registry.petuum.com/internal/pl/daisy/producer/prod

pylint:
  stage: verify
  tags: [docker_runner]
  image: python:3.6.1
  script:
    - pip install pylint==2.3.1
    - pylint nlp/ examples/

flake8:
  stage: verify
  tags: [docker_runner]
  image: python:3.6.1
  script:
    - pip install flake8==3.7.7
    - flake8 nlp/ examples/XK

mypy:
  stage: test
  tags: [docker_runner]
  image: python:3.6.1
  script:
    - pip3 install -q mypy==0.720
    - git clone https://github.com/asyml/texar-pytorch
    - cd texar-pytorch
    - pip3 install -q -e .
    - cd ..
    - pip3 install --no-cache-dir -q -e .[ner,srl,txtgen]
    - mypy .

pytest:
  stage: test
  tags: [docker_runner]
  image: python:3.6.1
  script:
    - pip3 install -q pytest
    - pip3 install -q -e .
    - git clone https://github.com/asyml/texar-pytorch
    - cd texar-pytorch
    - pip3 install -q -e .
    - cd ..
    - pip3 install --no-cache-dir -q -e .[ner,srl,txtgen]
    - pytest nlp/
