data:
  relative_path: "data/collectionandqueries"

reader:
  pack_name: "query"

query_creator:
  size: 5
  field: "content"
  query_pack_name: "query"

indexer:
  query_pack_name: "query"
  field: "content"
  response_pack_name_prefix: "passage"
  index_config:
    index_name: "elastic_indexer2"
    hosts: "localhost:9200"
    algorithm: "bm25"

NER:
  config_data:
    max_char_length: 45
    num_char_pad: 2

  config_model:

    resource_dir: "resources"

    output_hidden_size: 128
    dropout_rate: 0.3

    char_emb:
      dim: 30
      initializer:
        'type': 'normal_'

    char_cnn_conv:
      in_channels: 30
      out_channels: 30
      kernel_size: 3
      padding: 2

    bilstm_sentence_encoder:
      # Input size should be the sum of char_embed.dim and word_emb.dim
      rnn_cell_fw:
        input_size: 130
        type: LSTMCell
        kwargs:
          num_units: 128
      rnn_cell_share_config: yes
      output_layer_fw:
        num_layers: 0
      output_layer_share_config: yes

    initializer:
      "type": "xavier_uniform_"

    random_seed: 1234

writer:
  output_file: "output/results_eval.tsv"

evaluator:
  pack_name: "query"
  ground_truth_file: "data/collection_and_queries/query_doc_id.tsv"
  output_file: "output/results_dev.tsv"

reranker:
  size: 5
  pretrained_model_name: "bert-large-uncased"
  cache_dir: "models"
  query_pack_name: "query"
  field: "content"
  max_seq_length: 512
